# version: '2'
# services:
#   metamodel-membrane:
#     container_name: metamodel-membrane
#     image: apache/metamodel-membrane
#     ports:
#     - "8080:8080"
#     environment:
#     - MEMBRANE_HTTP_PORT=8080
#     depends_on:
#     - example-postgres
#     - example-couchdb
#   example-postgres:
#     container_name: example-postgres
#     image: postgres:9.6
#     environment:
#     - POSTGRES_USER=membrane
#     - POSTGRES_PASSWORD=secret
#     - POSTGRES_DB=membrane
#   example-couchdb:
#     container_name: example-couchdb
#     image: couchdb:1.6
#     environment:
#     - COUCHDB_USER=membrane
#     - COUCHDB_PASSWORD=secret
#     ports:
#     - 5984:5984


version: "3"
services: 
  couchdb:
    image: couchdb
    environment:
    - COUCHDB_USER=user
    - COUCHDB_PASSWORD=password
    ports:
    - 5984:5984
