/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type QueryResult = {
  users:
    | ({
        name: string | null;
      } | null)[]
    | null;
};
export type QueryVariables = {};
