/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type Login = {
  login: {
    id: string | null;
    valid: boolean | null;
    jwt: string | null;
    expiresAt: string | null;
  } | null;
};
export type LoginVariables = {
  name: string;
  password: string;
};
