/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type NewPost = {
  createPost: {
    title: string | null;
  } | null;
};
export type NewPostVariables = {
  title: string;
  content: string;
};
