/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type NewUser = {
  createUser: {
    name: string | null;
  } | null;
};
export type NewUserVariables = {
  username: string;
  password: string;
};
